### PR TITLE
mlx file added

### PR DESCRIPTION
**Pull request by Happypals**

### CODE REVIEW

**Comment by DTV96Calibre** [comment]
The file added was a binary. Remove that and add the changes to main.m

**Comment by Happypals** [comment]
I think you can open it with matlab.

**Comment by Happypals** [comment]
Did you edit main.m file in an editor?

**Comment by DTV96Calibre** [comment]
yeah, but even edited with MATLAB it was saved as a text file

**Comment by DTV96Calibre** [comment]
It's still a binary, but I've pull it anyway and will just move everything to plain text.

**Comment by Happypals** [comment]
yeah, it is a binary file in github. But once you downloaded it and open it
with matlab. It should show.

**Comment by DTV96Calibre** [comment]
The problem is binary files are useless with version control tools. The only thing that can be determined is that something changed, but not what. I have to download the changes, load matlab, and load the file to see what was changed examining line by line or using commandline diff instead of just using git/github

**Comment by Happypals** [comment]
Yeah, I don't know why. I'll just send you the file through the emails then.

**Pull request merged**
